//ESSE HEADER É DESTINADO PARA VARIAVÉVEIS E FUNÇÕES GLOBAIS DE USO GERAL
#ifndef GENERAL_H
	#define GENERAL_H

	extern const int DISPLAY_WIDTH;
	extern const int DISPLAY_HEIGHT;

#endif // !GENERAL_H

