#ifndef ELEMENT_H

	#define ELEMENT_H
	
	enum MIX_RESULTS
	{
		//Vida
		COMPATIBLE,
		//Dano
		ACID_BASE,
		REDOX,
		TOXIC_COMPOUND_FORMATION,
		//Status
		WATER_REACTIVITY,
		METAL_REACTIVITY
	};

	enum CHEMICAL_ELEMENTS
	{
		HCl,
		NaOH,
		H2SO4,
		KMnO4,
		H2O2,
		Cl2,
		NH3,
		NaClO,
		Na,
		Mg,
		Al,
		HNO3,
		Fe,
		Cu,
		Ag
	};

	extern const int ELEMENTS_AMOUNT;

	enum MIX_RESULTS mixElements(enum CHEMICAL_ELEMENTS elem1,
		enum CHEMICAL_ELEMENTS elem2);

	//STRUCT COM AS IMAGENS DOS ELEMENTOS

	typedef struct ELEMENTO ELEMENTO;

	struct ELEMENTO
	{
		ALLEGRO_BITMAP* HCl;
		ALLEGRO_BITMAP* NaOH;
		ALLEGRO_BITMAP* H2SO4;
		ALLEGRO_BITMAP* KMnO4;
		ALLEGRO_BITMAP* H2O2;
		ALLEGRO_BITMAP* Cl2;
		ALLEGRO_BITMAP* NH3;
		ALLEGRO_BITMAP* NaClO;
		ALLEGRO_BITMAP* Na;
		ALLEGRO_BITMAP* Mg;
		ALLEGRO_BITMAP* Al;
		ALLEGRO_BITMAP* HNO3;
		ALLEGRO_BITMAP* Fe;
		ALLEGRO_BITMAP* Cu;
		ALLEGRO_BITMAP* Ag;

		void (*destroyElemento)(ELEMENTO*);
	};

	ELEMENTO* initElemento();
#endif
